# Generated by Django 4.1.3 on 2024-05-21 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurant", "0004_rename_first_name_booking_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="comment",
            field=models.CharField(max_length=1000, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="full_name",
            field=models.CharField(max_length=200, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guest_number",
            field=models.IntegerField(verbose_name="Количество гостей"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="phone_number",
            field=models.IntegerField(null=True, verbose_name="Номер телефона"),
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.menu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
