# Generated by Django 4.1.3 on 2024-05-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_order_orderdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(default="", max_length=100),
        ),
    ]
